export const categories = [
  {
    id: "hot-dishes",
    name: { en: "Hot Dishes", ru: "Горячие блюда", kk: "Ыстық тағамдар" },
    image: "/IMG_8315.JPG",
    subcategories: [
      { id: "traditional", name: { en: "Traditional", ru: "Традиционные", kk: "Дәстүрлі" } },
      { id: "steaks", name: { en: "Steaks", ru: "Стейки", kk: "Стейктер" } },
      { id: "manti", name: { en: "Manti", ru: "Манты", kk: "Манты" } },
      { id: "kuyrdak", name: { en: "Kuyrdak", ru: "Куырдак", kk: "Қуырдақ" } },
    ],
  },
  {
    id: "fire-dishes",
    name: { en: "Dishes on Fire", ru: "Блюда на огне", kk: "Отта қуырылған тағамдар" },
    image: "/IMG_8355.PNG",
    subcategories: [
      { id: "kebabs", name: { en: "Kebabs", ru: "Кебабы", kk: "Кебаптар" } },
      { id: "shashlik", name: { en: "Shashlik", ru: "Шашлык", kk: "Шашлық" } },
    ],
  },
  {
    id: "soups",
    name: { en: "Soups", ru: "Супы", kk: "Көжелер" },
    image: "/IMG_8382.PNG",
    subcategories: [
      { id: "meat-soups", name: { en: "Meat Soups", ru: "Мясные супы", kk: "Еттен жасалған көжелер" } },
      { id: "fish-soups", name: { en: "Fish Soups", ru: "Рыбные супы", kk: "Балық көжелері" } },
    ],
  },
  {
    id: "bakery",
    name: { en: "Bakery", ru: "Выпечка", kk: "Қамыр тағамдары" },
    image: "/IMG_8364.PNG",
    subcategories: [
      { id: "bread", name: { en: "Bread", ru: "Хлеб", kk: "Нан" } },
      { id: "pastries", name: { en: "Pastries", ru: "Выпечка", kk: "Пісірілген тағамдар" } },
    ],
  },
  {
    id: "snacks",
    name: { en: "Snacks", ru: "Закуски", kk: "Жеңіл ас" },
    image: "/IMG_8400.PNG",
    subcategories: [
      { id: "cold-snacks", name: { en: "Cold Snacks", ru: "Холодные закуски", kk: "Суық тағамдар" } },
      { id: "hot-snacks", name: { en: "Hot Snacks", ru: "Горячие закуски", kk: "Ыстық тағамдар" } },
    ],
  },
  {
    id: "salads",
    name: { en: "Salads", ru: "Салаты", kk: "Салаттар" },
    image: "/IMG_8346.JPG",
    subcategories: [
      { id: "vegetable", name: { en: "Vegetable", ru: "Овощные", kk: "Көкөністі" } },
      { id: "meat-salads", name: { en: "With Meat", ru: "С мясом", kk: "Еттен жасалған" } },
    ],
  },
  {
    id: "drinks",
    name: { en: "Drinks", ru: "Напитки", kk: "Сусындар" },
    image: "/IMG_8591.PNG",
    subcategories: [
      { id: "traditional-drinks", name: { en: "Traditional", ru: "Традиционные", kk: "Дәстүрлі" } },
      { id: "lemonades", name: { en: "Lemonades", ru: "Лимонады", kk: "Лимонадтар" } },
      { id: "hot-drinks", name: { en: "Hot Drinks", ru: "Горячие напитки", kk: "Ыстық сусындар" } },
      { id: "milkshakes", name: { en: "Milkshakes", ru: "Милкшейки", kk: "Милкшейктер" } },
      { id: "ice-cream", name: { en: "Ice Cream", ru: "Мороженое", kk: "Балмұздақ" } },
    ],
  },

  {
    id: "pizza",
    name: { en: "Pizza & Pide", ru: "Пицца и пиде", kk: "Пицца және пиде" },
    image: "/IMG_8365.PNG",
    subcategories: [
      { id: "pizza", name: { en: "Pizza", ru: "Пицца", kk: "Пицца" } },
      { id: "pide", name: { en: "Pide", ru: "Пиде", kk: "Пиде" } },
      { id: "khachapuri", name: { en: "Khachapuri", ru: "Хачапури", kk: "Хачапури" } },
    ],
  },

]

export const menuItems = [
  // Hot Dishes - Traditional
  {
    id: 1,
    name: { en: "Besbarmak", ru: "Бесбармак", kk: "Бесбармақ" },
    description: { en: "Horse meat, kazy", ru: "Конина, казы", kk: "Жылқы еті, қазы" },
    image: "/besbarmak-kazakh-dish.jpg",
    sizes: [{ size: "", price: 3900 }],
    category: "hot-dishes",
    subcategory: "traditional",
  },
  {
    id: 2,
    name: { en: "Nomad Roll", ru: "Nomad roll", kk: "Nomad roll" },
    description: {
      en: "Horse ribs meat, bulgur and kumis",
      ru: "Реберное мясо конины, булгур и кумыс",
      kk: "Жылқының қабырға еті, булгур және қымыз",
    },
    image: "/IMG_8388.PNG",
    sizes: [{ size: "", price: 4800 }],
    category: "hot-dishes",
    subcategory: "traditional",
  },
  {
    id: 3,
    name: { en: "Fried Beef", ru: "Жареная говядина", kk: "Қуырылған сиыр еті" },
    description: {
      en: "Beef, pumpkin puree, buckwheat, demi-glace sauce",
      ru: "Говядина, тыквенное пюре, гречка, соус демиглас",
      kk: "Сиыр еті, асқабақ пюресі, гречка, демиглас соусы",
    },
    image: "/IMG_8290.JPG",
    sizes: [{ size: "", price: 5800 }],
    category: "hot-dishes",
    subcategory: "traditional",
  },
  {
    id: 4,
    name: { en: "Usharal Zander", ru: "Судак по-Ушаральски", kk: "Үшарал көксеркесі" },
    description: {
      en: "Zander fillet, potatoes, seaweed, pesto sauce, creamy sauce",
      ru: "Филе судака, картофель, морские водоросли, соус песто, сливочный соус",
      kk: "Судақ филесі, картоп, теңіз балдырлары, песто соусы, кремді соус",
    },
    image: "IMG_8306.JPG",
    sizes: [{ size: "", price: 4700 }],
    category: "hot-dishes",
    subcategory: "traditional",
  },
  {
    id: 5,
    name: { en: "Almaty Salmon", ru: "Алматинская семга", kk: "Алматы алабалық" },
    description: {
      en: "Salmon, sour cream sauce, vegetables in creamy sauce",
      ru: "Семга, сметанный соус, овощи в сливочном соусе",
      kk: "Семга, сметана соусы, кремді соустағы көкөністер",
    },
    image: "IMG_8299.JPG",
    sizes: [{ size: "", price: 5700 }],
    category: "hot-dishes",
    subcategory: "traditional",
  },
  // Hot Dishes - Steaks
  {
    id: 6,
    name: { en: "Horse Steak", ru: "Стейк из конины", kk: "Жылқы стейк" },
    description: {
      en: "Fire-grilled horse meat, ptitim pasta, pepper sauce",
      ru: "Конина на огне, паста птитим, перечный соус",
      kk: "Оттағы жылқы еті, птитим макарон, бұрыш соусы",
    },
    image: "IMG_8500.jpg",
    sizes: [{ size: "", price: 5200 }],
    category: "hot-dishes",
    subcategory: "steaks",
  },
  // Hot Dishes - Kuyrdak
  {
    id: 7,
    name: { en: "Tai Kuyrdak", ru: "Тай куырдак", kk: "Тай қуырдақ" },
    description: {
      en: "Foal meat, thin flatbread, potatoes, sour cream",
      ru: "Мясо жеребенка, тонкая лепешка, картофель, сметана",
      kk: "Тай еті, жұқа нан, картоп, сметана",
    },
    image: "/IMG_8387.PNG",
    sizes: [{ size: "", price: 4500 }],
    category: "hot-dishes",
    subcategory: "kuyrdak",
  },
  {
    id: 8,
    name: { en: "Chyz-Byz with Sour Cream", ru: "Чыз-быз со сметаной", kk: "Чыз-быз қаймақпен" },
    description: {
      en: "Beef tenderloin, potato wedges, sour cream, kurt",
      ru: "Говяжья вырезка, картофельные дольки, сметана, курт",
      kk: "Сиыр етінің филесі, картоп тілімдері, сметана, құрт",
    },
    image: "/IMG_8318.JPG",
    sizes: [{ size: "", price: 4700 }],
    category: "hot-dishes",
    subcategory: "kuyrdak",
  },
  {
    id: 9,
    name: { en: "Chyz-Byz with Katyk", ru: "Чыз-быз с катыком", kk: "Чыз-быз қатықпен" },
    description: {
      en: "Chopped beef, potato wedges, katyk, sweet chili sauce, kurt",
      ru: "Рубленая говядина, картофельные дольки, катык, соус сладкий чили, курт",
      kk: "Туралған сиыр еті, картоп тілімдері, қатық, тәтті чили соусы, құрт",
    },
    image: "IMG_8424.png",
    sizes: [{ size: "", price: 3900 }],
    category: "hot-dishes",
    subcategory: "kuyrdak",
  },
  {
    id: 10,
    name: { en: "Kazan Kebab", ru: "Казан-кебаб", kk: "Қазан кебаб" },
    description: { en: "Lamb, potatoes, onion", ru: "Баранина, картофель, лук", kk: "Қой еті, картоп, пияз" },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "", price: 4700 }],
    category: "hot-dishes",
    subcategory: "kuyrdak",
  },
  {
    id: 11,
    name: { en: "Taba Kuyrdak", ru: "Таба куырдак", kk: "Таба қуырдақ" },
    description: {
      en: "Lamb, vegetables, closed flatbread",
      ru: "Баранина, овощи, закрытая лепешка",
      kk: "Қой еті, көкөністер, жабық нан",
    },
    image: "/IMG_8315.JPG",
    sizes: [{ size: "", price: 4700 }],
    category: "hot-dishes",
    subcategory: "kuyrdak",
  },
  {
    id: 12,
    name: { en: "Bal Kuyrdak", ru: "Бал куырдак", kk: "Бал қуырдақ" },
    description: {
      en: "Beef/lamb, potato wedges, creamy sauce, herbs",
      ru: "Говядина/баранина, картофельные дольки, сливочный соус, зелень",
      kk: "Сиыр/қой еті, картоп тілімдері, кремді соус, жасылша",
    },
    image: "/IMG_8319.JPG",
    sizes: [{ size: "", price: 5200 }],
    category: "hot-dishes",
    subcategory: "kuyrdak",
  },
  {
    id: 13,
    name: { en: "Kumis Ribs", ru: "Ребрышки в кумысе", kk: "Қымыз қабырға" },
    description: {
      en: "Lamb ribs, bulgur, yogurt",
      ru: "Бараньи ребрышки, булгур, йогурт",
      kk: "Қой қабырғалары, булгур, йогурт",
    },
    image: "IMG_8501.jpg",
    sizes: [{ size: "", price: 4900 }],
    category: "hot-dishes",
    subcategory: "kuyrdak",
  },
  {
    id: 14,
    name: { en: "Orama Shuzhyk", ru: "Орама шужык", kk: "Орама шұжық" },
    description: {
      en: "Shuzhyk sausage, mashed potatoes, salsa sauce",
      ru: "Колбаса шужык, картофельное пюре, соус сальса",
      kk: "Шұжық шұжығы, картоп пюресі, сальса соусы",
    },
    image: "/IMG_8316.JPG",
    sizes: [{ size: "", price: 4600 }],
    category: "hot-dishes",
    subcategory: "traditional",
  },
  {
    id: 15,
    name: { en: "Khorezm Plov", ru: "Хорезмский плов", kk: "Хорезм палау" },
    description: { en: "Beef, rice", ru: "Говядина, рис", kk: "Сиыр еті, күріш" },
    image: "/IMG_8538.JPG",
    sizes: [{ size: "", price: 3400 }],
    category: "hot-dishes",
    subcategory: "traditional",
  },
  {
    id: 16,
    name: { en: "Maitash Chicken", ru: "Цыпленок Майташ", kk: "Майташ тауық" },
    description: {
      en: "Chicken fillet, potatoes, creamy sauce",
      ru: "Куриное филе, картофель, сливочный соус",
      kk: "Тауық филесі, картоп, кремді соус",
    },
    image: "/IMG_8321.JPG",
    sizes: [{ size: "", price: 3500 }],
    category: "hot-dishes",
    subcategory: "traditional",
  },
  // Hot Dishes - Manti
  {
    id: 17,
    name: { en: "Pumpkin Manti", ru: "Манты с тыквой", kk: "Асқабақ манты" },
    description: {
      en: "Beef, tail fat, onion, pumpkin, sour cream",
      ru: "Говядина, курдючный жир, лук, тыква, сметана",
      kk: "Сиыр еті, құйрық майы, пияз, асқабақ, сметана",
    },
    image: "/IMG_8309.JPG",
    sizes: [{ size: "", price: 2700 }],
    category: "hot-dishes",
    subcategory: "manti",
  },
  {
    id: 18,
    name: { en: "Manti", ru: "Манты", kk: "Манты" },
    description: { en: "Chopped beef, onion", ru: "Рубленая говядина, лук", kk: "Туралған сиыр еті, пияз" },
    image: "/IMG_8308.JPG",
    sizes: [{ size: "", price: 3300 }],
    category: "hot-dishes",
    subcategory: "manti",
  },
  // Dishes on Fire
  {
    id: 19,
    name: { en: "Chicken Shish", ru: "Куриный шиш", kk: "Тауық шиш" },
    description: {
      en: "Chicken meat, rice, onion, Dungan pepper, Turkish bread, lavash, red sauce",
      ru: "Куриное мясо, рис, лук, дунганский перец, турецкий хлеб, лаваш, красный соус",
      kk: "Тауық еті, күріш, пияз, дүнген бұрышы, түрік наны, лаваш, қызыл соус",
    },
    image: "/IMG_8347.JPG",
    sizes: [{ size: "", price: 2700 }],
    category: "fire-dishes",
    subcategory: "kebabs",
  },
  {
    id: 20,
    name: { en: "Chicken Wings", ru: "Куриные крылышки", kk: "Тауық қанат" },
    description: {
      en: "Chicken wings, rice, onion, Dungan pepper, Turkish bread, lavash, red sauce",
      ru: "Куриные крылышки, рис, лук, дунганский перец, турецкий хлеб, лаваш, красный соус",
      kk: "Тауық қанаттары, күріш, пияз, дүнген бұрышы, түрік наны, лаваш, қызыл соус",
    },
    image: "/IMG_8296.JPG",
    sizes: [{ size: "", price: 2700 }],
    category: "fire-dishes",
    subcategory: "kebabs",
  },
  {
    id: 21,
    name: { en: "Duck Sashlik", ru: "Шашлык из утки", kk: "Үйрек шашлык" },
    description: {
      en: "Duck meat, rice, onion, Dungan pepper, Turkish bread, lavash, red sauce",
      ru: "Мясо утки, рис, лук, дунганский перец, турецкий хлеб, лаваш, красный соус",
      kk: "Үйрек еті, күріш, пияз, дүнген бұрышы, түрік наны, лаваш, қызыл соус",
    },
    image: "/IMG_8294.JPG",
    sizes: [{ size: "", price: 2700 }],
    category: "fire-dishes",
    subcategory: "shashlik",
  },
  {
    id: 22,
    name: { en: "Adana Kebab", ru: "Адана кебаб", kk: "Адана кебаб" },
    description: {
      en: "Minced beef, rice, onion, Dungan pepper, Turkish bread, lavash, red sauce",
      ru: "Рубленая говядина, рис, лук, дунганский перец, турецкий хлеб, лаваш, красный соус",
      kk: "Туралған сиыр еті, күріш, пияз, дүнген бұрышы, түрік наны, лаваш, қызыл соус",
    },
    image: "/IMG_8355.PNG",
    sizes: [{ size: "", price: 3100 }],
    category: "fire-dishes",
    subcategory: "kebabs",
  },
  {
    id: 23,
    name: { en: "Zhapyrak Shashlik", ru: "Япрак шашлык", kk: "Жапырақ шашлык" },
    description: {
      en: "Beef tenderloin, tail fat, rice, onion, Dungan pepper, Turkish bread, lavash, red sauce",
      ru: "Говяжья вырезка, курдюк, рис, лук, дунганский перец, турецкий хлеб, лаваш, красный соус",
      kk: "Сиыр филесі, құйрық, күріш, пияз, дүнген бұрышы, түрік наны, лаваш, қызыл соус",
    },
    image: "/IMG_8286.JPG",
    sizes: [{ size: "", price: 3600 }],
    category: "fire-dishes",
    subcategory: "shashlik",
  },
  {
    id: 24,
    name: { en: "Izmir Kofte", ru: "Измир кёфте", kk: "Измир көпте" },
    description: {
      en: "Minced beef, rice, onion, Dungan pepper, Turkish bread, lavash, red sauce",
      ru: "Фарш из говядины, рис, лук, дунганский перец, турецкий хлеб, лаваш, красный соус",
      kk: "Сиыр фаршы, күріш, пияз, дүнген бұрышы, түрік наны, лаваш, қызыл соус",
    },
    image: "/IMG_8317.JPG",
    sizes: [{ size: "", price: 3600 }],
    category: "fire-dishes",
    subcategory: "kebabs",
  },
  {
    id: 25,
    name: { en: "Lamb Shashlik", ru: "Шашлык из баранины", kk: "Қой шашлык" },
    description: {
      en: "Lamb, rice, onion, Dungan pepper, Turkish bread, lavash, red sauce",
      ru: "Баранина, рис, лук, дунганский перец, турецкий хлеб, лаваш, красный соус",
      kk: "Қой еті, күріш, пияз, дүнген бұрышы, түрік наны, лаваш, қызыл соус",
    },
    image: "/IMG_8295.JPG",
    sizes: [{ size: "", price: 3600 }],
    category: "fire-dishes",
    subcategory: "shashlik",
  },
  {
    id: 26,
    name: { en: "Lula Kebab", ru: "Люля кебаб", kk: "Люля кебаб" },
    description: {
      en: "Beef, rice, onion, Dungan pepper, Turkish bread, lavash, red sauce",
      ru: "Говядина, рис, лук, дунганский перец, турецкий хлеб, лаваш, красный соус",
      kk: "Сиыр еті, күріш, пияз, дүнген бұрышы, түрік наны, лаваш, қызыл соус",
    },
    image: "/IMG_8353.PNG",
    sizes: [{ size: "", price: 3600 }],
    category: "fire-dishes",
    subcategory: "kebabs",
  },
  {
    id: 27,
    name: { en: "Pirzola", ru: "Пирзола", kk: "Пирзола" },
    description: {
      en: "Lamb rack, rice, Dungan pepper, Turkish bread, onion",
      ru: "Баранья корейка, рис, дунганский перец, турецкий хлеб, лук",
      kk: "Қой қабырғасы, күріш, дүнген бұрышы, түрік наны, пияз",
    },
    image: "/IMG_8520.PNG",
    sizes: [{ size: "", price: 3600 }],
    category: "fire-dishes",
    subcategory: "kebabs",
  },
  {
    id: 28,
    name: { en: "Grilled Vegetables", ru: "Овощи на огне", kk: "От көкөніс" },
    description: {
      en: "Vegetables grilled on open fire",
      ru: "Овощи, обжаренные на огне",
      kk: "Ашық отта қуырылған көкөністер",
    },
    image: "/IMG_8399.PNG",
    sizes: [{ size: "", price: 1700 }],
    category: "fire-dishes",
    subcategory: "kebabs",
  },
  // Soups
  {
    id: 29,
    name: { en: "Balkash", ru: "Балкаш", kk: "Балқаш" },
    description: {
      en: "Zander, fish broth, vegetables, herbs",
      ru: "Судак, рыбный бульон, овощи, зелень",
      kk: "Судақ, балық сорпасы, көкөністер, жасылша",
    },
    image: "/IMG_8345.JPG",
    sizes: [{ size: "", price: 2300 }],
    category: "soups",
    subcategory: "fish-soups",
  },
  {
    id: 30,
    name: { en: "Tushpara", ru: "Тушпара", kk: "Тұшпара" },
    description: {
      en: "Minced beef dumplings, herbs",
      ru: "Говяжий фарш, зелень",
      kk: "Сиыр фаршынан жасалған түшпара, жасылша",
    },
    image: "/IMG_8371.PNG",
    sizes: [{ size: "", price: 2300 }],
    category: "soups",
    subcategory: "meat-soups",
  },
  {
    id: 31,
    name: { en: "Naryn", ru: "Нарын", kk: "Нарын" },
    description: {
      en: "Finely cut dough, smoked kazy and horse meat, ayran",
      ru: "Тонко нарезанное тесто, вяленая казы и конина, айран",
      kk: "Жіңішке кесілген қамыр, кептірілген қазы және жылқы еті, айран",
    },
    image: "/IMG_8386.PNG",
    sizes: [{ size: "", price: 2300 }],
    category: "soups",
    subcategory: "meat-soups",
  },
  {
    id: 32,
    name: { en: "Kurt Kozhe", ru: "Курт коже", kk: "Құрт көже" },
    description: { en: "Horse meat, potatoes, kurt", ru: "Конина, картофель, курт", kk: "Жылқы еті, картоп, құрт" },
    image: "/IMG_8403.PNG",
    sizes: [{ size: "", price: 2100 }],
    category: "soups",
    subcategory: "meat-soups",
  },
  {
    id: 33,
    name: { en: "Kespe Kozhe", ru: "Кеспе коже", kk: "Кеспе көже" },
    description: { en: "Horse meat, noodles", ru: "Конина, лапша", kk: "Жылқы еті, кеспе" },
    image: "/IMG_8385.PNG",
    sizes: [{ size: "", price: 2100 }],
    category: "soups",
    subcategory: "meat-soups",
  },
  {
    id: 34,
    name: { en: "Duyin", ru: "Дуйин", kk: "Дүйін" },
    description: {
      en: "Lamb, Turkish ayran, butter",
      ru: "Баранина, турецкий айран, сливочное масло",
      kk: "Қой еті, түрік айраны, сары май",
    },
    image: "/IMG_8372.PNG",
    sizes: [{ size: "", price: 2100 }],
    category: "soups",
    subcategory: "meat-soups",
  },
  {
    id: 35,
    name: { en: "Ezogelin", ru: "Езогелин", kk: "Езогелін" },
    description: {
      en: "Lentils, red pepper, potatoes",
      ru: "Чечевица, красный перец, картофель",
      kk: "Жасымық, қызыл бұрыш, картоп",
    },
    image: "/IMG_8381.PNG",
    sizes: [{ size: "", price: 2100 }],
    category: "soups",
    subcategory: "meat-soups",
  },
  {
    id: 36,
    name: { en: "Shorpo", ru: "Шорпо", kk: "Шорпо" },
    description: {
      en: "Beef/lamb, potatoes, vegetables, herbs",
      ru: "Говядина/баранина, картофель, овощи, зелень",
      kk: "Сиыр/қой еті, картоп, көкөністер, жасылша",
    },
    image: "/IMG_8382.PNG",
    sizes: [{ size: "", price: 2100 }],
    category: "soups",
    subcategory: "meat-soups",
  },
  {
    id: 37,
    name: { en: "Biday Kozhe", ru: "Бидай коже", kk: "Бидай көже" },
    description: {
      en: "Kazy, horse meat, wheat, kurt",
      ru: "Казы, конина, пшеница, курт",
      kk: "Қазы, жылқы еті, бидай, құрт",
    },
    image: "/IMG_8383.PNG",
    sizes: [{ size: "", price: 2100 }],
    category: "soups",
    subcategory: "meat-soups",
  },
  // Bakery
  {
    id: 38,
    name: { en: "Taba Nan", ru: "Таба нан", kk: "Таба нан" },
    description: { en: "Pan-baked bread", ru: "Хлеб, испеченный в сковороде", kk: "Табада пісірілген нан" },
    image: "/IMG_8594.PNG",
    sizes: [{ size: "", price: 600 }],
    category: "bakery",
    subcategory: "bread",
  },
  {
    id: 39,
    name: { en: "Aktai Baursaks", ru: "Актай баурсаки", kk: "Ақтай бауырсақ" },
    description: {
      en: "Traditional fried dough",
      ru: "Традиционные жареные изделия из теста",
      kk: "Дәстүрлі қуырылған қамыр",
    },
    image: "IMG_8503.jpg",
    sizes: [{ size: "", price: 600 }],
    category: "bakery",
    subcategory: "pastries",
  },
  {
    id: 40,
    name: { en: "Myzhyma Nan", ru: "Мыжыма нан", kk: "Мыжыма нан" },
    description: {
      en: "Crushed flatbread with butter",
      ru: "Лепешка со сливочным маслом",
      kk: "Сары майлы жұмсақ нан",
    },
    image: "IMG_8497.jpg",
    sizes: [{ size: "", price: 600 }],
    category: "bakery",
    subcategory: "bread",
  },
  {
    id: 41,
    name: { en: "Meat Samsa", ru: "Самса с мясом", kk: "Ет самса" },
    description: {
      en: "Puff pastry with meat filling",
      ru: "Слоеное тесто с мясной начинкой",
      kk: "Қабатты қамырдан жасалған етті самса",
    },
    image: "IMG_8505.jpg",
    sizes: [{ size: "", price: 900 }],
    category: "bakery",
    subcategory: "pastries",
  },
  {
    id: 42,
    name: { en: "Kattama", ru: "Каттама", kk: "Қаттама" },
    description: { en: "Layered flatbread", ru: "Слоеная лепешка", kk: "Қабатты нан" },
    image: "/IMG_8398.PNG",
    sizes: [{ size: "", price: 900 }],
    category: "bakery",
    subcategory: "bread",
  },
  {
    id: 43,
    name: { en: "Zhuka Nan", ru: "Жука нан", kk: "Жұқпа нан" },
    description: { en: "Thin flatbread", ru: "Тонкая лепешка", kk: "Жұқа нан" },
    image: "/IMG_8397.PNG",
    sizes: [{ size: "", price: 800 }],
    category: "bakery",
    subcategory: "bread",
  },
  {
    id: 44,
    name: { en: "Bread Basket", ru: "Хлебная корзина", kk: "Нан себет" },
    description: {
      en: "Aktai baursaks, meat samsa, myzhyma nan, taba nan, black bread, cottage cheese baursaks",
      ru: "Актай баурсаки, самса с мясом, мыжыма нан, таба нан, черный хлеб, творожные баурсаки",
      kk: "Ақтай бауырсақтар, етті самса, мыжыма нан, таба нан, қара нан, сүзбе бауырсақтар",
    },
    image: "/IMG_8364.PNG",
    sizes: [{ size: "", price: 3900 }],
    category: "bakery",
    subcategory: "pastries",
  },
  {
    id: 45,
    name: { en: "Irimshik-Baursaks", ru: "Творожные баурсаки", kk: "Ірімшік - бауырсақ" },
    description: {
      en: "Sweet cheese balls, fluffy dough",
      ru: "Красный творог/иримшик, воздушное тесто",
      kk: "Ірімшік, жұмсақ қамыр",
    },
    image: "IMG_8423.png",
    sizes: [{ size: "", price: 1200 }],
    category: "bakery",
    subcategory: "pastries",
  },
  // Snacks
  {
    id: 46,
    name: { en: "Turan Platter", ru: "Туран табак", kk: "Тұран табақ" },
    description: {
      en: "Smoked suluguni, mini mozzarella, kazy, horse meat roast beef, smoked zhal, aromatic oil, baguette, oat flakes",
      ru: "Копченый сулугуни, мини-моцарелла, казы, ростбиф из конины, копченый жал, ароматное масло, багет, овсяные хлопья",
      kk: "Ысталған сулугуни, шағын моцарелла, қазы, жылқы етінің ростбифі, ысталған жал, хош иісті май, багет, сұлы дәндері",
    },
    image: "IMG_8504.jpg",
    sizes: [{ size: "", price: 4600 }],
    category: "snacks",
    subcategory: "cold-snacks",
  },
  {
    id: 47,
    name: { en: "Chytyr Manti", ru: "Чытыр манты", kk: "Чытыр манты" },
    description: {
      en: "Fried manti with beef and mashed potatoes",
      ru: "Говядина, картофельное пюре",
      kk: "Сиыр еті, картоп пюресі",
    },
    image: "/IMG_8389.PNG",
    sizes: [{ size: "", price: 3100 }],
    category: "snacks",
    subcategory: "hot-snacks",
  },
  {
    id: 48,
    name: { en: "Uyz Kazy", ru: "Уыз казы", kk: "Уыз қазы" },
    description: {
      en: "Kazy, bryndza cheese, cherry tomatoes",
      ru: "Казы, сыр брынза, помидоры черри",
      kk: "Қазы, брынза ірімшігі, шерри қызанақ",
    },
    image: "/IMG_8400.PNG",
    sizes: [{ size: "", price: 3100 }],
    category: "snacks",
    subcategory: "cold-snacks",
  },
  // Salads
  {
    id: 49,
    name: { en: "Choban", ru: "Чобан", kk: "Чобан" },
    description: {
      en: "Vegetable tartare, olive oil, tortilla",
      ru: "Овощной тар-тар, оливковое масло, тортилья",
      kk: "Көкөніс тар-тары, зәйтүн майы, тортилья",
    },
    image: "/IMG_8303.JPG",
    sizes: [{ size: "", price: 2200 }],
    category: "salads",
    subcategory: "vegetable",
  },
  {
    id: 50,
    name: { en: "Achuchuk", ru: "Ачу-чук", kk: "Ачу-чук" },
    description: {
      en: "Smoked cheese, tomatoes, red onion, cilantro",
      ru: "Копченый сыр, помидоры, красный лук, кинза",
      kk: "Ысталған ірімшік, қызанақ, қызыл пияз, кинза",
    },
    image: "/IMG_8305.JPG",
    sizes: [{ size: "", price: 2200 }],
    category: "salads",
    subcategory: "vegetable",
  },
  {
    id: 51,
    name: { en: "Caucasus", ru: "Кавказ", kk: "Кавказ" },
    description: {
      en: "Fresh vegetables, white cheese, herbs",
      ru: "Свежие овощи, белый сыр, зелень",
      kk: "Жаңа көкөністер, ақ ірімшік, жасылша",
    },
    image: "/IMG_8310.JPG",
    sizes: [{ size: "", price: 2500 }],
    category: "salads",
    subcategory: "vegetable",
  },
  {
    id: 52,
    name: { en: "Zhaylau", ru: "Жайлау", kk: "Жайлау" },
    description: {
      en: "Aioli sauce, grilled chicken, parmesan, herbs, green peas",
      ru: "Соус айоли, курица на гриле, пармезан, зелень, зеленый горошек",
      kk: "Айоли соусы, гриль тауық, пармезан, жасылша, жасыл бұршақ",
    },
    image: "/zhailau.JPG",
    sizes: [{ size: "", price: 2800 }],
    category: "salads",
    subcategory: "meat-salads",
  },
  {
    id: 53,
    name: { en: "Boz Dala", ru: "Боз дала", kk: "Боз дала" },
    description: {
      en: "Beef, smoked chicken, cucumbers, potatoes, signature sauce",
      ru: "Говядина, копченая курица, огурцы, картофель, авторский соус",
      kk: "Сиыр еті, ысталған тауық, қияр, картоп, фирмалық соус",
    },
    image: "/IMG_8301.JPG",
    sizes: [{ size: "", price: 2900 }],
    category: "salads",
    subcategory: "meat-salads",
  },
  {
    id: 54,
    name: { en: "Bakhar", ru: "Бахар", kk: "Бахар" },
    description: {
      en: "Zucchini, tomatoes, bryndza cheese, arugula, lettuce, pesto sauce, walnuts",
      ru: "Кабачки, помидоры, сыр брынза, руккола, листья салата, соус песто, грецкие орехи",
      kk: "Кабачок, қызанақ, брынза ірімшігі, рукола, салат жапырақтары, песто соусы, грек жаңғағы",
    },
    image: "/IMG_8401.PNG",
    sizes: [{ size: "", price: 3000 }],
    category: "salads",
    subcategory: "vegetable",
  },
  {
    id: 55,
    name: { en: "Borsha Et", ru: "Борша ет", kk: "Борша ет" },
    description: {
      en: "Arugula, grilled horse meat, vegetables, signature sauce",
      ru: "Руккола, конина на гриле, овощи, авторский соус",
      kk: "Рукола, гриль жылқы еті, көкөністер, фирмалық соус",
    },
    image: "/IMG_8346.JPG",
    sizes: [{ size: "", price: 3200 }],
    category: "salads",
    subcategory: "meat-salads",
  },
  {
    id: 56,
    name: { en: "Bukhara", ru: "Бухара", kk: "Бұхара" },
    description: {
      en: "Chicken schnitzel, crispy eggplant, tomatoes, cilantro, sweet chili sauce",
      ru: "Куриный шницель, хрустящие баклажаны, помидоры, кинза, соус сладкий чили",
      kk: "Тауық шницелі, қытырлақ баклажан, қызанақ, кинза, тәтті чили соусы",
    },
    image: "/IMG_8297.JPG",
    sizes: [{ size: "", price: 3500 }],
    category: "salads",
    subcategory: "meat-salads",
  },
  {
    id: 57,
    name: { en: "Koktem", ru: "Коктем", kk: "Көктем" },
    description: {
      en: "Burrata, tomatoes, raspberry sauce, vegetables",
      ru: "Буратта, помидоры, малиновый соус, овощи",
      kk: "Буратта, қызанақ, таңқурай соусы, көкөністер",
    },
    image: "/IMG_8304.JPG",
    sizes: [{ size: "", price: 3600 }],
    category: "salads",
    subcategory: "vegetable",
  },
  // Drinks - Traditional
  {
    id: 58,
    name: { en: "Ayran", ru: "Айран", kk: "Айран" },
    description: {
      en: "Traditional fermented milk drink",
      ru: "Традиционный кисломолочный напиток",
      kk: "Дәстүрлі сүт сусыны",
    },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "0,2 л", price: 500 }],
    category: "drinks",
    subcategory: "traditional-drinks",
  },
  {
    id: 59,
    name: { en: "Kumis", ru: "Кумыс", kk: "Қымыз" },
    description: { en: "Fermented mare's milk", ru: "Кисломолочный напиток из кобыльего молока", kk: "Қымыз" },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [
      { size: "1 л", price: 2200 },
      { size: "0,5 л", price: 1200 },
    ],
    category: "drinks",
    subcategory: "traditional-drinks",
  },
  {
    id: 60,
    name: { en: "Blackcurrant mors", ru: "Морс из черный смородины", kk: "Қарақат морс" },
    description: {
      en: "Refreshing blackcurrant drink",
      ru: "Освежающий напиток из черной смородины",
      kk: "Қара қарақаттан жасалған сергітетін сусын",
    },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [
      { size: "1 л", price: 2200 },
      { size: "0,5 л", price: 1200 },
    ],
    category: "drinks",
    subcategory: "traditional-drinks",
  },
  {
    id: 61,
    name: { en: "Turan water", ru: "Туран вода", kk: "Тұран су" },
    description: { en: "Natural mineral water", ru: "Натуральная минеральная вода", kk: "Табиғи минералды су" },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "", price: 500 }],
    category: "drinks",
    subcategory: "traditional-drinks",
  },
  // Drinks - Lemonades
  {
    id: 62,
    name: { en: "Mojito", ru: "Мохито", kk: "Мохито" },
    description: {
      en: "Classic mojito lemonade",
      ru: "Классический лимонад мохито",
      kk: "Классикалық мохито лимонады",
    },
    image: "IMG_8491.jpg",
    sizes: [
      { size: "1 л", price: 2600 },
      { size: "0,5 л", price: 1300 },
    ],
    category: "drinks",
    subcategory: "lemonades",
  },
  {
    id: 63,
    name: { en: "Mango & Passion fruit", ru: "Манго-маракуйя", kk: "Манго-маракуйя" },
    description: {
      en: "Tropical mango and passion fruit",
      ru: "Манго и маракуйя",
      kk: "Тропикалық манго мен маракуйя",
    },
    image: "IMG_8502.jpg",
    sizes: [
      { size: "1 л", price: 2600 },
      { size: "0,5 л", price: 1300 },
    ],
    category: "drinks",
    subcategory: "lemonades",
  },
  {
    id: 64,
    name: { en: "Berry mix", ru: "Ягодный", kk: "Жидектер" },
    description: { en: "Mixed berries lemonade", ru: "Ягодный лимонад", kk: "Жидек лимонады" },
    image: "IMG_8493.jpg",
    sizes: [
      { size: "1 л", price: 2600 },
      { size: "0,5 л", price: 1300 },
    ],
    category: "drinks",
    subcategory: "lemonades",
  },
  {
    id: 65,
    name: { en: "Kiwi & Banana", ru: "Киви-банан", kk: "Киви-банан" },
    description: { en: "Kiwi and banana blend", ru: "Киви и банан", kk: "Киви мен банан" },
    image: "IMG_84915jpg",
    sizes: [
      { size: "1 л", price: 2600 },
      { size: "0,5 л", price: 1300 },
    ],
    category: "drinks",
    subcategory: "lemonades",
  },
  {
    id: 66,
    name: { en: "Currant & Passion Fruit", ru: "Смородина-маракуйя", kk: "Қарақат-маракуйя" },
    description: { en: "Currant and passion fruit blend", ru: "Смородина и маракуйя", kk: "Қарақат пен маракуйя" },
    image: "IMG_8499.jpg",
    sizes: [
      { size: "1 л", price: 2600 },
      { size: "0,5 л", price: 1300 },
    ],
    category: "drinks",
    subcategory: "lemonades",
  },
  {
    id: 67,
    name: { en: "Cucumber & Apple", ru: "Огурец-яблока", kk: "Қияр-алма" },
    description: {
      en: "Refreshing cucumber and apple",
      ru: "Освежающий огуречно-яблочный",
      kk: "Сергітетін қияр мен алма",
    },
    image: "IMG_8496.jpg",
    sizes: [
      { size: "1 л", price: 2600 },
      { size: "0,5 л", price: 1300 },
    ],
    category: "drinks",
    subcategory: "lemonades",
  },
  {
    id: 68,
    name: {
      en: "Orange, Sea Buckthorn & Cinnamon",
      ru: "Апельсин, облепиха, корица",
      kk: "Апельсин, шырғанақ, корица",
    },
    description: {
      en: "Warming orange, sea buckthorn with cinnamon",
      ru: "Согревающий апельсин, облепиха и корица",
      kk: "Жылытатын апельсин, шырғанақ пен дарчын",
    },
    image: "IMG_8494.jpg",
    sizes: [
      { size: "1 л", price: 2600 },
      { size: "0,5 л", price: 1300 },
    ],
    category: "drinks",
    subcategory: "lemonades",
  },
  {
    id: 69,
    name: { en: "Pomegranate", ru: "Грантовый", kk: "Анар" },
    description: { en: "Fresh pomegranate lemonade", ru: "Гранатовый лимонад", kk: "Анар лимонады" },
    image: "IMG_8492.jpg",
    sizes: [
      { size: "1 л", price: 2600 },
      { size: "0,5 л", price: 1300 },
    ],
    category: "drinks",
    subcategory: "lemonades",
  },
  {
    id: 70,
    name: { en: "Chamomile & Cherry", ru: "Ромашка-вишня", kk: "Түймедақ-шие" },
    description: { en: "Chamomile tea with cherry", ru: "Ромашка с вишней", kk: "Түймедақ пен шие" },
    image: "IMG_8498.jpg",
    sizes: [
      { size: "1 л", price: 2600 },
      { size: "0,5 л", price: 1300 },
    ],
    category: "drinks",
    subcategory: "lemonades",
  },
  // Drinks - Hot Drinks / Teas
  {
    id: 71,
    name: { en: "Black Tea", ru: "Черный", kk: "Қара шай" },
    description: { en: "Classic black tea", ru: "Классический черный чай", kk: "Классикалық қара шай" },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [
      { size: "шәйнек", price: 1500 },
      { size: "кесе", price: 400 },
    ],
    category: "drinks",
    subcategory: "hot-drinks",
  },
  {
    id: 72,
    name: { en: "Green Tea", ru: "Зеленый", kk: "Көк шай" },
    description: { en: "Premium green tea", ru: "Зеленый чай премиум", kk: "Премиум жасыл шай" },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [
      { size: "шәйнек", price: 1500 },
      { size: "кесе", price: 400 },
    ],
    category: "drinks",
    subcategory: "hot-drinks",
  },
  {
    id: 73,
    name: { en: "Tea with Milk", ru: "С молоком", kk: "Сүтті шай" },
    description: { en: "Traditional tea with milk", ru: "Традиционный чай с молоком", kk: "Дәстүрлі сүтті шай" },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [
      { size: "шәйнек", price: 1600 },
      { size: "кесе", price: 500 },
    ],
    category: "drinks",
    subcategory: "hot-drinks",
  },
  {
    id: 74,
    name: { en: "Tashkent Tea", ru: "Ташкентский", kk: "Ташкент шайы" },
    description: { en: "Traditional Tashkent style tea", ru: "Чай по-ташкентски", kk: "Ташкент стиліндегі шай" },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "", price: 2500 }],
    category: "drinks",
    subcategory: "hot-drinks",
  },
  {
    id: 75,
    name: { en: "Tea with Tara (millet)", ru: "С Тары", kk: "Тары шай" },
    description: { en: "Tea with millet", ru: "Чай с тары (просо)", kk: "Тары қосылған шай" },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "", price: 2500 }],
    category: "drinks",
    subcategory: "hot-drinks",
  },
  {
    id: 76,
    name: { en: "Turkish Tea", ru: "Турецкий", kk: "Түрік шай" },
    description: { en: "Strong Turkish black tea", ru: "Крепкий турецкий черный чай", kk: "Күшті түрік қара шайы" },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "", price: 2500 }],
    category: "drinks",
    subcategory: "hot-drinks",
  },
  {
    id: 77,
    name: { en: "Sea Buckthorn & Orange", ru: "Облепиха-апельсин", kk: "Шырғанақ-апельсин" },
    description: {
      en: "Hot sea buckthorn with orange",
      ru: "Горячий напиток из облепихи и апельсина",
      kk: "Ыстық шырғанақ пен апельсин",
    },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "", price: 2800 }],
    category: "drinks",
    subcategory: "hot-drinks",
  },
  {
    id: 78,
    name: { en: "Fruit & Berry tea", ru: "Фрукто-ягодный", kk: "Жеміс-жидек" },
    description: { en: "Mixed fruit and berry infusion", ru: "Фруктово-ягодный чай", kk: "Жеміс және жидек қоспасы" },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "", price: 2800 }],
    category: "drinks",
    subcategory: "hot-drinks",
  },
  // Drinks - Milkshakes
  {
    id: 79,
    name: { en: "Oreo", ru: "Орео", kk: "Орео" },
    description: { en: "Creamy Oreo milkshake", ru: "Сливочный милкшейк с Орео", kk: "Кремді Орео милкшейкі" },
    image: "/IMG_8427.PNG",
    sizes: [{ size: "0,5 л", price: 1600 }],
    category: "drinks",
    subcategory: "milkshakes",
  },
  {
    id: 80,
    name: { en: "Chocolate", ru: "Шоколадный", kk: "Шоколад" },
    description: { en: "Rich chocolate milkshake", ru: "Насыщенный шоколадный милкшейк", kk: "Қою шоколадты милкшейк" },
    image: "/IMG_8426.PNG",
    sizes: [{ size: "0,5 л", price: 1600 }],
    category: "drinks",
    subcategory: "milkshakes",
  },
  {
    id: 81,
    name: { en: "Strawberry", ru: "Клубничный", kk: "Құлпынай" },
    description: { en: "Fresh strawberry milkshake", ru: "Клубничный милкшейк", kk: "Жаңа құлпынай милкшейкі" },
    image: "/IMG_8425.PNG",
    sizes: [{ size: "0,5 л", price: 1600 }],
    category: "drinks",
    subcategory: "milkshakes",
  },
  {
    id: 82,
    name: { en: "Vanilla", ru: "Ванильный", kk: "Ваниль" },
    description: {
      en: "Classic vanilla milkshake",
      ru: "Классический ванильный милкшейк",
      kk: "Классикалық ванильді милкшейк",
    },
    image: "/IMG_8429.jpg",
    sizes: [{ size: "0,5 л", price: 1600 }],
    category: "drinks",
    subcategory: "milkshakes",
  },
  {
    id: 83,
    name: { en: "Blackcurrant", ru: "Смородиновый", kk: "Қарақат" },
    description: {
      en: "Blackcurrant flavored milkshake",
      ru: "Милкшейк со вкусом смородины",
      kk: "Қарақат дәмді милкшейк",
    },
    image: "/IMG_8428.PNG",
    sizes: [{ size: "0,5 л", price: 1600 }],
    category: "drinks",
    subcategory: "milkshakes",
  },
  {
    id: 84,
    name: { en: "Banana", ru: "Банановый", kk: "Банан" },
    description: { en: "Creamy banana milkshake", ru: "Сливочный банановый милкшейк", kk: "Кремді банан милкшейкі" },
    image: "/IMG_8430 (1).jpg",
    sizes: [{ size: "0,5 л", price: 1600 }],
    category: "drinks",
    subcategory: "milkshakes",
  },
  // Drinks - Ice Cream
  {
    id: 85,
    name: { en: "Vanilla", ru: "Ванильный", kk: "Ваниль" },
    description: {
      en: "Classic vanilla ice cream",
      ru: "Классическое ванильное мороженое",
      kk: "Классикалық ванильді балмұздақ",
    },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "", price: 600 }],
    category: "drinks",
    subcategory: "ice-cream",
  },
  {
    id: 86,
    name: { en: "Chocolate", ru: "Шоколадный", kk: "Шоколад" },
    description: {
      en: "Rich chocolate ice cream",
      ru: "Насыщенное шоколадное мороженое",
      kk: "Қою шоколадты балмұздақ",
    },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "", price: 600 }],
    category: "drinks",
    subcategory: "ice-cream",
  },
  {
    id: 87,
    name: { en: "Strawberry", ru: "Клубничный", kk: "Құлпынай" },
    description: { en: "Fresh strawberry ice cream", ru: "Клубничное мороженое", kk: "Жаңа құлпынай балмұздағы" },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "", price: 600 }],
    category: "drinks",
    subcategory: "ice-cream",
  },
  {
    id: 88,
    name: { en: "Pistachio", ru: "Фисташковый", kk: "Фисташка" },
    description: { en: "Creamy pistachio ice cream", ru: "Фисташковое мороженое", kk: "Кремді фисташка балмұздағы" },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "", price: 600 }],
    category: "drinks",
    subcategory: "ice-cream",
  },
  {
    id: 89,
    name: { en: "Nut", ru: "Ореховый", kk: "Жаңғақ" },
    description: { en: "Nutty flavored ice cream", ru: "Ореховое мороженое", kk: "Жаңғақ дәмді балмұздақ" },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "", price: 600 }],
    category: "drinks",
    subcategory: "ice-cream",
  },
  {
    id: 90,
    name: { en: "Bubble Gum", ru: "Бабл гам", kk: "Бабл гам" },
    description: {
      en: "Fun bubble gum flavored ice cream",
      ru: "Мороженое со вкусом жвачки",
      kk: "Бабл гам дәмді балмұздақ",
    },
    image: "/placeholder.svg?height=112&width=112",
    sizes: [{ size: "", price: 600 }],
    category: "drinks",
    subcategory: "ice-cream",
  },
  // Pizza
  {
    id: 97,
    name: { en: "Nomad", ru: "Номад", kk: "Номад" },
    description: {
      en: "Kazy, red onion, sour cream",
      ru: "Казы, красный лук, сметана",
      kk: "Қазы, қызыл пияз, сметана",
    },
    image: "/IMG_8365.PNG",
    sizes: [{ size: "", price: 3500 }],
    category: "pizza",
    subcategory: "pizza",
  },
  {
    id: 98,
    name: { en: "Margherita", ru: "Маргарита", kk: "Маргарита" },
    description: {
      en: "Mozzarella cheese, tomatoes, tomato sauce",
      ru: "Сыр моцарелла, томаты, томатный соус",
      kk: "Моцарелла ірімшігі, қызанақ, қызанақ соусы",
    },
    image: "IMG_8490.jpg",
    sizes: [{ size: "", price: 2500 }],
    category: "pizza",
    subcategory: "pizza",
  },
  {
    id: 99,
    name: { en: "Pepperoni", ru: "Пепперони", kk: "Пепперони" },
    description: {
      en: "Mozzarella cheese, tomatoes, pepperoni, tomato sauce",
      ru: "Сыр моцарелла, томаты, пепперони, томатный соус",
      kk: "Моцарелла ірімшігі, қызанақ, пепперони, қызанақ соусы",
    },
    image: "/IMG_8369.PNG",
    sizes: [{ size: "", price: 3200 }],
    category: "pizza",
    subcategory: "pizza",
  },
  {
    id: 100,
    name: { en: "Chicken Mozzarella", ru: "Курица-моцарелла", kk: "Тауық-моцарелла" },
    description: {
      en: "Chicken fillet, tomatoes, mozzarella cheese, creamy sauce",
      ru: "Куриное филе, томаты, сыр моцарелла, сливочный соус",
      kk: "Тауық филесі, қызанақ, моцарелла ірімшігі, кремді соус",
    },
    image: "/IMG_8311.JPG",
    sizes: [{ size: "", price: 3200 }],
    category: "pizza",
    subcategory: "pizza",
  },
  // Pide
  {
    id: 101,
    name: { en: "Pide Karishik", ru: "Пиде Карышик", kk: "Қарышық пиде" },
    description: {
      en: "Mozzarella cheese, suluguni cheese, dough",
      ru: "Сыр моцарелла, сыр сулугуни, тесто",
      kk: "Моцарелла ірімшігі, сулугуни ірімшігі, қамыр",
    },
    image: "/IMG_8314.JPG",
    sizes: [{ size: "", price: 3200 }],
    category: "pizza",
    subcategory: "pide",
  },
  {
    id: 102,
    name: { en: "Pide Mevlana", ru: "Пиде Мевлана", kk: "Мевлана пиде" },
    description: {
      en: "Lamb, dough, fresh herbs",
      ru: "Баранина, тесто, свежая зелень",
      kk: "Қой еті, қамыр, жаңа жасылша",
    },
    image: "/IMG_8368.PNG",
    sizes: [{ size: "", price: 3200 }],
    category: "pizza",
    subcategory: "pide",
  },
  // Khachapuri
  {
    id: 103,
    name: { en: "Puff Pastry Khachapuri", ru: "Слоеное хачапури", kk: "Қатпарлы хачапури" },
    description: {
      en: "Puff pastry, mozzarella cheese, suluguni cheese, butter",
      ru: "Слоеное тесто, сыр моцарелла, сыр сулугуни, масло",
      kk: "Қабатты қамыр, моцарелла ірімшігі, сулугуни ірімшігі, май",
    },
    image: "/IMG_8313.JPG",
    sizes: [{ size: "", price: 3200 }],
    category: "pizza",
    subcategory: "khachapuri",
  },
  {
    id: 104,
    name: { en: "Baku-style Khachapuri", ru: "Хачапури по-бакински", kk: "Баку хачапури" },
    description: { en: "Cheese, egg", ru: "Сыр, яйцо", kk: "Ірімшік, жұмыртқа" },
    image: "/IMG_8363.PNG",
    sizes: [{ size: "", price: 3200 }],
    category: "pizza",
    subcategory: "khachapuri",
  },
]
export const translations = {
  search: { en: "Search menu...", ru: "Поиск...", kk: "Іздеу..." },
  noItems: {
    en: "No items found. Try a different search or category.",
    ru: "Ничего не найдено. Попробуйте другой поиск или категорию.",
    kk: "Ештеңе табылмады. Басқа іздеу немесе санатты көріңіз.",
  },
  searchResults: {
    en: "Results found",
    ru: "Найдено результатов",
    kk: "Нәтижелер табылды",
  },
}